service: cocnonkp

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1

functions:
  CoCNonKP:
    handler: lambda_function.lambda_handler

plugins:
  - serverless-python-requirements
