on:
  push:
    branches:
      - master

name: Deploy to Amazon Lambda

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Dependency Packages
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        pip3 install awscli
        pip3 install requests -t .
        zip -x .git -r lambda.zip ./*
        mv lambda.zip /tmp/lambda.zip
        aws lambda update-function-code --function-name CoCNonKP --zip-file fileb:///tmp/lambda.zip --publish

    - name: Notify result to slack
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Deploy Lambda*'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
